apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    component: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mariadb-deployment
  template:
    metadata:
      labels:
        component: mariadb-deployment
    spec:
      containers:
        - name: mariadb-deployment
          image: mariadb
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'root'
            - name: MYSQL_DATABASE
              value: 'shrtdb'
            - name: MYSQL_USER
              value: 'admin'
            - name: MYSQL_PASSWORD
              value: 'supersecret'